books = Category.create(id: 1, name: 'Books')
games = Category.create(id: 2, name: 'Games')
furniture = Category.create(id: 3, name: 'Furniture')
kitchen = Category.create(id: 4, name: 'Kitchen')

Product.create!(id: 1, name: 'Book One', category: books, price: '40,00')
Product.create!(id: 2, name: 'Game One', category: games, price: '43,90')
Product.create!(id: 3, name: 'A Nice Chair', category: furniture, price: '83,95')
Product.create!(id: 4, name: 'Trash Can', category: kitchen, price: '21,00')
Product.create!(id: 5, name: 'Game Two', category: games, price: '43,90')
